accounts/urls.py
''' accounts/urls.py '''
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'accounts'  # pylint: disable=invalid-name

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logged_out.html'),
         name='logout'),
]

memorable_places/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('memories/', include('memories.urls', namespace='memories')),
    path('', views.home, name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('social-auth/', include('social_django.urls', namespace="social")),
]

urlpatterns += staticfiles_urlpatterns()  # for DEBUG = True

memories/urls.py
from django.urls import path

from . import views

app_name = 'memories'  # pylint: disable=invalid-name

urlpatterns = [
    path('', views.index),
    path('list/', views.MemoriesListView.as_view(), name='list'),
    path('create/', views.MemoriesCreateView.as_view(), name='create'),
    path('delete/<int:uid>', views.delete_memory, name='delete'),
    path('details/<int:pk>', views.MemoryDetailsView.as_view(), name='details'),
]

accounts/models.py
''' accounts/models.py '''
from django.db import models  # pylint: disable=unused-import

# Create your models here.

memories/models.py
''' memories/models.py '''
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class MemoryItem(models.Model):
    ''' Memory Item '''
    name = models.CharField(max_length=64)
    comment = models.TextField()
    longitude = models.CharField(max_length=64, default=60.60388)
    latitude = models.CharField(max_length=64, default=56.8444)
    owner = models.ForeignKey(User, on_delete=models.CASCADE,
                              related_name='memories')

    def __str__(self):
        ''' Magic method '''
        return self.name

    def get_absolute_url(self):
        ''' Get absolute url '''
        return reverse("memories:details", args=[self.pk])

accounts/forms.py
''' accounts/forms.py '''
from django import forms
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    ''' Login Form '''
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class RegistrationForm(forms.ModelForm):
    ''' Registration Form '''
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput)

    class Meta:
        ''' Meta '''
        model = User
        fields = ("username", "email", "first_name")
        labels = {"username": 'Логин', "email": 'Email', "first_name": 'Имя'}

        def clean_password2(self) -> str:
            ''' Check password are the same '''
            clean_data = self.cleaned_data  # pylint: disable=no-member
            if clean_data["password"] != clean_data["password2"]:
                raise forms.ValidationError("Пароли не совпадают")
            return clean_data["password2"]

memories/forms.py
''' memories/forms.py '''
from django import forms

from memories.models import MemoryItem


class MemoryItemForm(forms.ModelForm):
    ''' Memory Form '''
    class Meta:
        ''' Meta class '''
        model = MemoryItem
        fields = ('name', 'comment', 'longitude', 'latitude')
        labels = {"name": "Название", "comment": "Комментарий"}
        widgets = {"comment": forms.Textarea(attrs={'rows': 5}),
                   "longitude": forms.HiddenInput(),
                   "latitude": forms.HiddenInput()}

accounts/views.py
'''accounts/views.py'''
from django.contrib.auth import authenticate, login
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.views import View

from accounts.forms import LoginForm, RegistrationForm


class LoginView(View):
    '''LoginView'''
    @classmethod
    def post(cls, request: HttpRequest) -> HttpResponse:
        '''post'''
        form = LoginForm(request.POST)
        if form.is_valid():
            cleande_data = form.cleaned_data
            user = authenticate(
                request,
                username=cleande_data['username'],
                password=cleande_data['password']
            )
            if user is None:
                return HttpResponse('Неправильный логин и/или пароль')

            if not user.is_active:  # type: ignore[attr-defined]
                return HttpResponse('Ваш аккаунт заблокирован')

            login(request, user)
            return HttpResponse('Добро пожаловать! Успешный вход')
        return render(request, 'accounts/login.html', {'form': form})

    @classmethod
    def get(cls, request: HttpRequest) -> HttpResponse:
        '''get'''
        form = LoginForm()
        return render(request, 'accounts/login.html', {'form': form})


def register(request: HttpRequest) -> HttpResponse:
    '''register'''
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data["password"])
            new_user.save()
            return render(request, "accounts/registration_complete.html",
                          {"new_user": new_user})
    else:
        form = RegistrationForm()

    return render(request, "accounts/register.html", {"user_form": form})

memorable_places/views.py
''' memorable_places/views '''
from django.shortcuts import render


def home(request):
    ''' View of home page '''
    return render(request, 'home.html')

memories/views.py
''' memories/views.py '''
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views import View
from django.views.generic import ListView
from django.views.generic.detail import DetailView

from memories.forms import MemoryItemForm
from memories.models import MemoryItem


@login_required
def index(request):  # pylint: disable=unused-argument
    ''' Index '''
    return HttpResponse('Ваши воспоминания Туть')


class MemoriesListView(ListView):
    ''' Memories List View '''
    queryset = MemoryItem.objects.all()  # pylint: disable=no-member
    context_object_name = 'memories'
    template_name = "memories/list.html"

    def get_queryset(self):
        ''' Get queryset '''
        user = self.request.user
        if user.is_anonymous:
            return []
        return user.memories.all()


class MemoriesCreateView(View):
    ''' Memories Create View '''
    @classmethod
    def my_render(cls, request, form, **kwargs):
        ''' Render method '''
        return render(request, "memories/create.html", {"form": form,
                                                        "mapbox_token": kwargs['mapbox_token']})

    def post(self, request):
        ''' Post '''
        form = MemoryItemForm(request.POST)
        if form.is_valid():
            new_memory = form.save(commit=False)
            new_memory.owner = request.user
            new_memory.save()
            return redirect(reverse(viewname="memories:list"))
        return self.my_render(request, form)

    def get(self, request):
        ''' Get '''
        form = MemoryItemForm()
        return self.my_render(request, form, mapbox_token=settings.MAPBOX_TOKEN)


class MemoryDetailsView(DetailView):
    ''' Memory Details View '''
    model = MemoryItem
    template_name = 'memories/details.html'
    extra_context = {"mapbox_token": settings.MAPBOX_TOKEN}


def delete_memory(request, uid):  # pylint: disable=unused-argument
    ''' Delete memory '''
    memory = MemoryItem.objects.get(id=uid)  # pylint: disable=no-member
    memory.delete()
    return redirect(reverse(viewname="memories:list"))

accounts/templates/accounts/logged_out.html
{% extends "base.html" %}
{% block title %}Вы вышли{% endblock %}
{% block main_content %}
<h1>Вы вышли.</h1>
<p>Сессия работы с сайтом завершена. Всегда можно <a href={% url "accounts:login"%}>залогининться и вернуться обратно</a>
</br></br>
<a href={% url "home"%}>Вернуться на страницу home</a>
{% endblock %}

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% block title %}Войдите{% endblock %}
{% block main_content %}
{% if not user.is_authenticated %}
<h1>Вход</h1>
{% if form.errors %}
<p>Ошибка: пароль или логин неправильные. Попробуйте снова</p>
{% else %}
<p>введите логин/пароль:</p>
{% endif %}

<form action="." method="POST" class="login">
    {{ form.as_p }}
    {% csrf_token %}
    <button class='btn-primary mp-3' style="color:black" type="submit">Войти</button>
</form>
</br>

<button class='btn-primary mp-3'><a style="color:black" href={% url "accounts:register" %}>Зарегистрироваться</a></button>
</br></br>


<p>Или вы можете войти через Facebook:</p>
<div class="row">
    <div class="col-md-8 mx-auto social-container my-2 order-md-1">
        <button class="btn btn-primary mb-2">
            <a style="color:black" href={% url 'social:begin' 'facebook' %}>Facebook</a>
        </button>
    </div>
</div>
{% else %}
<p>Вы уже вошли</p>
{% endif %}
{% endblock %}

accounts/templates/accounts/register.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block main_content %}
    <h1>Создать аккаунт</h1>
    <p>Воспользуйтесь следующей формой:</p>
    <form action="." method="post">
        {% for field in user_form %}
        <div class='field'>
            {{ field.label_tag }} {{ field }}
            {{ field.errors }}
        </div>
        {% endfor %}
        {% csrf_token %}
    <p><input type="submit" value="Создать"></p>
    </form>
{% endblock %}

accounts/templates/accounts/registration_complete.html
{% extends "base.html" %}
{% block title %}Ура! Успех{% endblock %}
{% block main_content %}
    <h1>Всё готово, {{ new_user.first_name }}!</h1>
    <p>Ваш аккаунт был создал, теперь можно <a href={% url "accounts:login"%}>залогиниться</a>.</p>
{% endblock %}

memories/templates/memories/create.html
{% extends "base.html" %}
{% block title %}Создать воспоминание{% endblock %}
{% block extra_head %}
<script src="https://api.mapbox.com/mapbox-gl-js/v1.11.1/mapbox-gl.js"></script>
<link href="https://api.mapbox.com/mapbox-gl-js/v1.11.1/mapbox-gl.css" rel="stylesheet" />
{% endblock %}

{% block main_content %}
<style>
	#map { position: absolute; top: 320px; bottom: -340px; width: 100%;}
</style>
<h1>Создать воспоминание</h1>
<form action="." method="post" class="memories-create">
    {% for field in form %}
        <div class='field'>
            {% if not field.is_hidden %}
                {{ field.label_tag }} {{ field }}
            {% else %}
                {{ field }}
            {% endif %}
            {{ field.errors }}
        </div>
    {% endfor %}
    {% csrf_token %}
    <button class="add" type="submit">Сохранить</button>
</form>
</br>
<div id="map"></div>
<style>
    .coordinates {
    background: rgba(0, 0, 0, 0.5);
    color: #fff;
    position: absolute;
    bottom: -270px;
    left: 10px;
    padding: 5px 10px;
    margin: 0;
    font-size: 11px;
    line-height: 18px;
    border-radius: 3px;
    display: none;
    }
</style>

<pre id="coordinates" class="coordinates"></pre>

<script>
	mapboxgl.accessToken = "{{ mapbox_token }}";
    var coordinates = document.getElementById('coordinates');
    var map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/mapbox/streets-v11',
    center: [60.60388, 56.8444],
    zoom: 7
    });
    
    var marker = new mapboxgl.Marker({
    draggable: true
    })
    .setLngLat([60.60388, 56.8444])
    .addTo(map);
    
    function onDragEnd() {
    var lngLat = marker.getLngLat();
    coordinates.style.display = 'block';
    coordinates.innerHTML =
    'Longitude: ' + lngLat.lng + '<br />Latitude: ' + lngLat.lat;
    }
    
    marker.on('dragend', onDragEnd);

    function saveCoordinates() {
        document.querySelector('[name=longitude]').value =
            marker.getLngLat().lng;
        document.querySelector('[name=latitude]').value =
            marker.getLngLat().lat;
    }
    marker.on('dragend', saveCoordinates);
</script>
{% endblock %}

memories/templates/memories/details.html
{% extends "base.html" %}
{% load static %}
{% block title %}Воспоминание {{ object.id }}{% endblock %}
{% block extra_head %}
    <meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no" />
    <script src="https://api.mapbox.com/mapbox-gl-js/v1.11.1/mapbox-gl.js"></script>
    <link href="https://api.mapbox.com/mapbox-gl-js/v1.11.1/mapbox-gl.css" rel="stylesheet" />
    <style>
        body { margin: 0; padding: 0; }
        #map { position: absolute; top: 200px; bottom: -340px; width: 100%; }
    </style>
{% endblock %}
{% block main_content %}
    <h1>Воспоминание</h1>
    <ul>
        <li>Название: {{ object.name }}</li>
        <li>Комментарий: {{ object.comment }}</li>
    </ul>
    <a href={% url "memories:list" %}>Назад к списку</a>
    <div id="map"></div>
 
    <script>
        mapboxgl.accessToken = "{{ mapbox_token }}";
        var map = new mapboxgl.Map({
            container: 'map',
            style: 'mapbox://styles/mapbox/streets-v11',
            center: ["{{ object.longitude }}", "{{ object.latitude }}"],
            zoom: 8
        });
        
        var marker = new mapboxgl.Marker()
            .setLngLat(["{{ object.longitude }}", "{{ object.latitude }}"])
            .addTo(map);
    </script>
{% endblock %}

memories/templates/memories/list.html
{% extends "base.html" %}
{% block title %}Ваши воспоминания{% endblock %}
{% block main_content %}
<div class="container">
    <h1>Ваши воспоминания</h1>
    <ul id="memory-list">
        {% if not memories %}
            <p>У вас пока ни одного воспоминания</p>
        {% endif %}
        {% for memory in memories %}
        <li>
            <a href={% url "memories:details" memory.id %}>{{ memory.name }}</a>
            <a class="remove" href={% url "memories:delete" memory.id %}>X</a>
            <hr/>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Воспоминания{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
        <script src="http://code.jquery.com/jquery-3.3.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
        {% block extra_head %}
        {% endblock %}
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="side_bar col">
                    {% block side_bar %}
                    {% if user.is_authenticated %}
                    <h1>{{ user.first_name }}</h1>
                    <ul>
                        <li><i class="fa fa-plus"></i>&nbsp;<a href="{% url 'memories:create' %}">добавить воспоминание</a></li>
                        <li><i class="fas fa-clipboard-list"></i>&nbsp;<a href="{% url 'memories:list' %}">Воспоминания</a></li>
                        <li><i class="fa fa-sign-out-alt"></i>&nbsp;<a href="{% url 'accounts:logout' %}">выйти</a></li>
                    </ul>
                    {% endif %}
                    {% endblock %}
                    </div>
                    <div class="main_content col-8">
                    <div class="main_content col-8">                    
                    {% block main_content %}
                    {% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block main_content %}
    <h1>Архив ваших воспоминаний</h1>
    <p>Здесь вы можете отметить, где вы бывали и оставить комментарий об этом месте.</p>
    <a href={% url "accounts:login" %}>Войти</a></br>
    <a href={% url "accounts:register" %}>Зарегистрироваться</a>
{% endblock %}